name: clean-chat
channels:
  - defaults
  - pytorch
dependencies:
  - python>=3.9
  - pip
  - pip:
      - tensorflow<2.11
      - google-generativeai
      - torch==2.1.0+cu121
      - torchvision==0.16.0+cu121
      - torchaudio==2.1.0+cu121
